server {
    listen 3000;
    server_name _;
    root /usr/share/nginx/html;

    location = /accustandard/demo {
        return 308 /accustandard/demo/;
    }

    location /accustandard/demo/ {
        try_files $uri $uri/ /accustandard/demo/index.html;
    }
}
