server {
    listen 3000;
    server_name _;
    root /usr/share/nginx/html;

    location = /demo/accustandard {
        return 308 /demo/accustandard/;
    }

    location /demo/accustandard/ {
        rewrite ^/demo/accustandard(/.*)$ $1 break;
        try_files $uri $uri/ /index.html;
    }

    location = /prod/accustandard {
        return 308 /prod/accustandard/;
    }

    location /prod/accustandard/ {
        rewrite ^/prod/accustandard(/.*)$ $1 break;
        try_files $uri $uri/ /index.html;
    }
}
