server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location = /healthz {
        access_log off;
        add_header Content-Type text/plain;
        return 200 'ok\n';
    }

    location /demo/accustandard/api/ {
        proxy_pass http://api:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /demo/accustandard {
        return 308 /demo/accustandard/;
    }

    location /demo/accustandard/ {
        rewrite ^/demo/accustandard(/.*)$ $1 break;
        try_files $uri $uri/ /index.html;
    }

    location = /prod/accustandard {
        return 308 /prod/accustandard/;
    }

    location /prod/accustandard/api/ {
        proxy_pass http://api:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /prod/accustandard/ {
        rewrite ^/prod/accustandard(/.*)$ $1 break;
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
